trigger:
- development

pool:
  vmImage: ubuntu-latest

variables:
  projectFolder: 'src'
  buildOutputFolder: 'dist'

strategy:
  matrix:
    node_12_x:
      node_version: 12.x
    node_14_x:
      node_version: 14.x

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'development'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)'
    OverWrite: true

- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    pushd $(projectFolder) && npm install && popd
    pushd $(projectFolder) && npm run build && popd

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(projectFolder)/$(buildOutputFolder)'
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
